# Generated by Django 4.0.5 on 2022-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_produto_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avalilable',
            field=models.BooleanField(default=False),
        ),
    ]
