# Generated by Django 4.0.5 on 2022-06-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_product_avalilable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalilable',
            new_name='available',
        ),
    ]
